services:
  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: .
    command: ["./worker-entrypoint.sh"]
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    extra_hosts:
      - "host.docker.internal:host-gateway"
